# No version :3

# Was made with the help of AI (lmm actually)
#   and a bit edited by me.

# === data sourcing
# 1. python-rest-api
# === hadoop map reduce with yarn
# 2. hdfs-namenode
# 3. hdfs-datanode
# 4. yarn-resourcemanager
# 5. yarn-nodemanager
# === spark pyspark jupyter notebook
# 6. spark-jupyter
# === postgres pgadmin4
# 7. postgres
# 8. pgadmin4
# === clickhouse
# 9. clickhouse
# === airflow
# 10. redis
# 11. airflow-apiserver
# 12. airflow-scheduler
# 13. airflow-dag-processor
# 14. airflow-worker
# 15. airflow-triggerer
# 16. airflow-init
# 17. airflow-cli
# 18. flower
# === net vol

x-airflow-common:
  &airflow-common
  #image: apache/airflow:3.3.1-python3.14
  build:
    context: .
    dockerfile: Dockerfile
  networks:
    - data-net
  env_file:
    - ${ENV_FILE_PATH:-.env}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://officeguy:Test4321@db-postgres/customs_db
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql+psycopg2://officeguy:Test4321@db-postgres/customs_db
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__API__SECRET_KEY: ${AIRFLOW__API__SECRET_KEY:-OG_airflow}
    AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW__API_AUTH__JWT_SECRET:-airflow_jwt_secret}
    AIRFLOW__API_AUTH__JWT_ISSUER: ${AIRFLOW__API_AUTH__JWT_ISSUER:-airflow}
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
    #_PIP_ADDITIONAL_REQUIREMENTS: "selenium webdriver-manager"
  volumes:
    - ./step_06_airflow/dags:/opt/airflow/dags
    - ./step_06_airflow/logs:/opt/airflow/logs
    - ./step_06_airflow/config:/opt/airflow/config
    - ./step_06_airflow/plugins:/opt/airflow/plugins
    - ./data_share:/app/data_share
    - ./step_02_hadoop_map_reduce:/cst_scripts
    - ./step_03_spark_aggregation:/cst_spark/spark_aggregation
    - ./step_04_postgres_datamart:/cst_pg_preparation
    - ./step_05_clickhouse:/cst_clickhouse #just in case
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    db-postgres:
      condition: service_healthy

# ===================
# ===================
# SERVICES START HERE
services:
# ========== step_01_data_sourcing
# 1. python-rest-api
  python-rest-api:
    image: python:3.14.6
    container_name: python-rest-api
    #restart: always
    hostname: python-rest-api
    networks:
      - data-net
    volumes:
      - ./step_01_data_sourcing:/app/scripts
      - ./data_share:/app/data_share                     
      - ./requirements.txt:/app/requirements.txt #httpx==0.27.0
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install -r /app/requirements.txt && tail -f /dev/null"

# ========== step_02_hadoop_map_reduce
# 2. hdfs-namenode
  hdfs-namenode:
    image: apache/hadoop:3.5.0
    container_name: hdfs-namenode
    restart: always
    hostname: hdfs-namenode
    user: root
    networks:
      - data-net
    ports:
      - "9870:9870"                   # Web UI HDFS
      - "9000:9000"                   # RPC
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data_share:/data_share                  
      - ./step_02_hadoop_map_reduce:/scripts
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - CORE-SITE.XML_fs.defaultFS=hdfs://hdfs-namenode:9000
      # it's local laptop run
      - HDFS-SITE.XML_dfs.replication=1
      - HDFS-SITE.XML_dfs.permissions.enabled=false
      - HDFS-SITE.XML_dfs.namenode.name.dir=/hadoop/dfs/name
      - HDFS-SITE.XML_dfs.datanode.data.dir=/hadoop/dfs/data
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y openssh-server &&
        mkdir -p /run/sshd &&
        chmod 0755 /run/sshd &&
        echo 'root:airflow123' | chpasswd &&
        mkdir -p /root/.ssh &&
        chmod 700 /root/.ssh &&
        cp /scripts/k.pub /root/.ssh/authorized_keys &&
        chmod 600 /root/.ssh/authorized_keys &&
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        /usr/sbin/sshd &&
        if [ ! -d /hadoop/dfs/name/current ]; 
          then hdfs namenode -format -force -nonInteractive;
        fi && hdfs namenode"
    healthcheck:
      test: ["CMD", "hdfs", "dfsadmin", "-safemode", "wait"]
      interval: 60s
      retries: 5
      start_period: 60s

# 3. hdfs-datanode
  hdfs-datanode:
    image: apache/hadoop:3.5.0
    container_name: hdfs-datanode
    restart: always
    hostname: hdfs-datanode
    user: root
    networks:
      - data-net
    ports:
      - "9864:9864"                   # Web UI DataNode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ./data_share:/data_share
      - ./step_02_hadoop_map_reduce:/scripts 
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - CORE-SITE.XML_fs.defaultFS=hdfs://hdfs-namenode:9000
      # it's local laptop run
      - HDFS-SITE.XML_dfs.replication=1
      - HDFS-SITE.XML_dfs.permissions.enabled=false
    #  - HDFS-SITE.XML_dfs.namenode.name.dir=/hadoop/dfs/name
      - HDFS-SITE.XML_dfs.datanode.data.dir=/hadoop/dfs/data
    depends_on:
      - hdfs-namenode #:
        #condition: service_healthy
    command: ["hdfs", "datanode"]

# 4. yarn-resourcemanager
  yarn-resourcemanager:
    image: apache/hadoop:3.5.0
    container_name: yarn-resourcemanager
    hostname: yarn-resourcemanager
    restart: always
    user: root
    networks:
      - data-net
    ports:
      - "8088:8088"        # Web UI YARN
      - "8030:8030"        # Scheduler
      - "8031:8031"        # Resource Tracker
      - "8032:8032"        # Address
      - "8033:8033"        # Admin
    volumes:
      - ./data_share:/data_share
      - ./step_02_hadoop_map_reduce:/scripts
    environment:
      - CORE-SITE.XML_fs.defaultFS=hdfs://hdfs-namenode:9000
      - HDFS-SITE.XML_dfs.replication=1
      - HDFS-SITE.XML_dfs.permissions.enabled=false
      - YARN_RESOURCEMANAGER_USER=root
      # ResourceManager settings
      - YARN-SITE.XML_yarn.resourcemanager.hostname=yarn-resourcemanager
      - YARN-SITE.XML_yarn.resourcemanager.address=yarn-resourcemanager:8032
      - YARN-SITE.XML_yarn.resourcemanager.scheduler.address=yarn-resourcemanager:8030
      - YARN-SITE.XML_yarn.resourcemanager.resource-tracker.address=yarn-resourcemanager:8031
      - YARN-SITE.XML_yarn.log-aggregation-enable=true
      - YARN-SITE.XML_yarn.nodemanager.aux-services=mapreduce_shuffle
      - MAPRED-SITE.XML_mapreduce.framework.name=yarn
      - MAPRED-SITE.XML_mapreduce.jobhistory.address=historyserver:10020
      - MAPRED-SITE.XML_mapreduce.jobhistory.webapp.address=historyserver:19888
      - YARN-SITE.XML_yarn.nodemanager.env-whitelist="JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_MAPRED_HOME"
      - MAPRED-SITE.XML_yarn.app.mapreduce.am.env-whitelist="JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_MAPRED_HOME"
    depends_on:
      - hdfs-namenode #:
        #condition: service_healthy
    command: ["yarn", "resourcemanager"]

# 5. yarn-nodemanager
  yarn-nodemanager:
    image: apache/hadoop:3.5.0
    container_name: yarn-nodemanager
    restart: always
    hostname: yarn-nodemanager
    user: root
    networks:
      - data-net
    ports:
      - "8042:8042"        # Web UI NodeManager
    volumes:
      - ./data_share:/data_share
      - ./step_02_hadoop_map_reduce:/scripts
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - YARN_RESOURCEMANAGER_USER=root
      - YARN_NODEMANAGER_USER=root
      - YARN-SITE.XML_yarn.nodemanager.local-dirs=/hadoop/yarn/local
      - YARN-SITE.XML_yarn.nodemanager.log-dirs=/hadoop/yarn/logs
      # HDFS connection
      - CORE-SITE.XML_fs.defaultFS=hdfs://hdfs-namenode:9000
      - HDFS-SITE.XML_dfs.replication=1
      - HDFS-SITE.XML_dfs.permissions.enabled=false
      # YARN connection
      - YARN-SITE.XML_yarn.resourcemanager.hostname=yarn-resourcemanager
      - YARN-SITE.XML_yarn.resourcemanager.address=yarn-resourcemanager:8032
      - YARN-SITE.XML_yarn.resourcemanager.scheduler.address=yarn-resourcemanager:8030
      - YARN-SITE.XML_yarn.resourcemanager.resource-tracker.address=yarn-resourcemanager:8031
      - YARN-SITE.XML_yarn.log-aggregation-enable=true
      - YARN-SITE.XML_yarn.nodemanager.aux-services=mapreduce_shuffle
      - MAPRED-SITE.XML_mapreduce.framework.name=yarn
      - MAPRED-SITE.XML_mapreduce.jobhistory.address=historyserver:10020
      - MAPRED-SITE.XML_mapreduce.jobhistory.webapp.address=historyserver:19888
      - YARN-SITE.XML_yarn.nodemanager.env-whitelist=JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_MAPRED_HOME
      - MAPRED-SITE.XML_yarn.app.mapreduce.am.env-whitelist=JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_MAPRED_HOME
    depends_on:
      - yarn-resourcemanager #:
        #condition: service_started
      - hdfs-datanode #:
        #condition: service_started
    command: ["yarn", "nodemanager"]

# ========== step_03_spark_aggregation
# 6. spark-jupyter
  spark-jupyter:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: spark-jupyter
    hostname: spark-jupyter
    restart: always
    networks:
      - data-net
    ports:
      - "8888:8888"                   # Jupyter Notebook
      - "4040:4040"                   # Spark Web UI 
    volumes:
      - ./step_03_spark_aggregation:/home/jovyan/work/spark_aggregation           # I still don't understand who tf is Jovyan
      - ./step_04_postgres_datamart:/home/jovyan/work/pg_preparation
      - ./data_share:/home/jovyan/work/data_share
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      # HDFS connection (maybe remove, probs useless)
      - SPARK_OPTS=--master local[*] --conf spark.hadoop.fs.defaultFS=hdfs://hdfs-namenode:9000
    depends_on:
      - hdfs-namenode #:
        # condition: service_healthy
    command: >
      sh -c "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

# ========== step_04_postgres_datamart
# 7. postgres
  db-postgres:
    image: postgres:18.4
    container_name: db-postgres
    restart: always
    networks:
      - data-net
    ports:
    - "5432:5432"
    volumes:
      - ./step_04_postgres_datamart:/host_data
      - ./data_share:/data_share
      - postgres-db-volume:/var/lib/postgresql
    environment:
    # IT'S A LOCAL TEST, NOT A PROD
      - POSTGRES_USER=officeguy
      - POSTGRES_PASSWORD=Test4321
      - POSTGRES_DB=customs_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "officeguy" ]
      interval: 10s
      retries: 5
      start_period: 5s

# 8. pgadmin4
  db-pgadmin4:
    image: dpage/pgadmin4:9.17
    container_name: db-pgadmin4
    restart: always
    networks:
      - data-net
    ports:
    - "5080:80"
    volumes:
      - ./step_04_postgres_datamart:/var/lib/pgadmin/storage
    environment:
    # IT'S A LOCAL TEST, NOT A PROD
      - PGADMIN_DEFAULT_EMAIL=officeguy@admin.com
      - PGADMIN_DEFAULT_PASSWORD=Test4321

# ========== step_05_clickhouse
# 9. clickhouse
  clickhouse:
    image: clickhouse:26.7.3
    container_name: db-clickhouse
    restart: always
    networks:
      - data-net
    ports:
      - "8123:8123"
      - "9001:9000"
      - "9009:9009"
    volumes:
      - ./step_05_clickhouse/_appdata:/var/lib/clickhouse
      - ./data_share:/data_share
    environment:
      - CLICKHOUSE_DB=CH_DB
      - CLICKHOUSE_USER=OFFICE_GUY
      - CLICKHOUSE_PASSWORD=Test4321
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGMENT=1

# ========== step_06_airflow
# 10. redis
  redis:
    # Redis is limited to 7.2-bookworm due to licencing change
    # https://redis.io/blog/redis-adopts-dual-source-available-licensing/
    image: redis:7.2-bookworm
    container_name: redis
    hostname: redis
    networks:
      - data-net
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

# 11. airflow-apiserver
  airflow-apiserver:
    <<: *airflow-common
    container_name: airflow-apiserver
    command: api-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

# 12. airflow-scheduler
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

# 13. airflow-dag-processor
  airflow-dag-processor:
    <<: *airflow-common
    container_name: airflow-dag-processor
    command: dag-processor
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

# 14. airflow-worker
  airflow-worker:
    <<: *airflow-common
    container_name: airflow-worker
    hostname: airflow-worker
    command: celery worker
    expose:
      - 8793
    healthcheck:
      # yamllint disable rule:line-length
      test: ["CMD-SHELL", 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      # Required to handle warm shutdown of the celery workers properly
      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-apiserver:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

# 15. airflow-triggerer
  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow-triggerer
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

# 16. airflow-init
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
          export AIRFLOW_UID=$$(id -u)
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        echo
        echo "Creating missing opt dirs if missing:"
        echo
        mkdir -v -p /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Airflow version:"
        /entrypoint airflow version
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Running airflow config list to create default config file if missing."
        echo
        /entrypoint airflow config list >/dev/null
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Change ownership of files in /opt/airflow to ${AIRFLOW_UID:-50000}:0"
        echo
        chown -R "${AIRFLOW_UID:-50000}:0" /opt/airflow/
        echo
        echo "Change ownership of files in shared volumes to ${AIRFLOW_UID:-50000}:0"
        echo
        chown -v -R "${AIRFLOW_UID:-50000}:0" /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}

    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"

# 17. airflow-cli
  airflow-cli:
    <<: *airflow-common
    container_name: airflow-cli
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
    command:
      - bash
      - -c
      - airflow
    depends_on:
      <<: *airflow-common-depends-on

# 18. flower
  flower:
    <<: *airflow-common
    container_name: airflow-flower
    command: celery flower
    profiles:
      - flower
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

# ========== Net Vol
networks:
  data-net:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode:
  postgres-db-volume: