# No version :3

# !!!!!!!
# ON 10.08.2026 postgres and pgadmin are added
# !!!!!!!

# Was made with the help of AI (lmm actually)
#   and a bit edited by me.

# === data soursing
# 1. python-rest-api
# === hadoop map reduce with yarn
# 2. hdfs-namenode
# 3. hdfs-datanode
# 4. yarn-resourcemanager
# 5. yarn-nodemanager
# === spark pyspark jupyter notebook
# 6. spark-jupyter
# === postgres pgadmin4
# 7. postgres
# 8. pgadmin4
# === net vol

services:
# ========== step_01_data_sourcing
# 1. python-rest-api
  python-rest-api:
    image: python:3.14.6
    container_name: python-rest-api
    hostname: python-rest-api
    networks:
      - data-net
    volumes:
      - ./step_01_data_sourcing:/app/scripts
      - ./data_share:/app/data_share                     
      - ./requirements.txt:/app/requirements.txt #httpx==0.27.0
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install -r /app/requirements.txt && tail -f /dev/null"

# ========== step_02_hadoop_map_reduce
# 2. hdfs-namenode
  hdfs-namenode:
    image: apache/hadoop:3.5.0
    container_name: hdfs-namenode
    restart: always
    hostname: hdfs-namenode
    user: root
    networks:
      - data-net
    ports:
      - "9870:9870"                   # Web UI HDFS
      - "9000:9000"                   # RPC
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data_share:/data_share                  
      - ./step_02_hadoop_map_reduce:/scripts
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - CORE-SITE.XML_fs.defaultFS=hdfs://hdfs-namenode:9000
      # it's local laptop run
      - HDFS-SITE.XML_dfs.replication=1
      - HDFS-SITE.XML_dfs.permissions.enabled=false
      - HDFS-SITE.XML_dfs.namenode.name.dir=/hadoop/dfs/name
      - HDFS-SITE.XML_dfs.datanode.data.dir=/hadoop/dfs/data
    command: >
      bash -c "if [ ! -d /hadoop/dfs/name/current ]; then
                   hdfs namenode -format -force -nonInteractive;
                 fi && hdfs namenode"
    healthcheck:
      test: ["CMD", "hdfs", "dfsadmin", "-safemode", "wait"]
      interval: 60s
      retries: 5
      start_period: 60s

# 3. hdfs-datanode
  hdfs-datanode:
    image: apache/hadoop:3.5.0
    container_name: hdfs-datanode
    restart: always
    hostname: hdfs-datanode
    user: root
    networks:
      - data-net
    ports:
      - "9864:9864"                   # Web UI DataNode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ./data_share:/data_share
      - ./step_02_hadoop_map_reduce:/scripts 
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - CORE-SITE.XML_fs.defaultFS=hdfs://hdfs-namenode:9000
      # it's local laptop run
      - HDFS-SITE.XML_dfs.replication=1
      - HDFS-SITE.XML_dfs.permissions.enabled=false
    #  - HDFS-SITE.XML_dfs.namenode.name.dir=/hadoop/dfs/name
      - HDFS-SITE.XML_dfs.datanode.data.dir=/hadoop/dfs/data
    depends_on:
      - hdfs-namenode #:
        #condition: service_healthy
    command: ["hdfs", "datanode"]

# 4. yarn-resourcemanager
  yarn-resourcemanager:
    image: apache/hadoop:3.5.0
    container_name: yarn-resourcemanager
    hostname: yarn-resourcemanager
    restart: always
    user: root
    networks:
      - data-net
    ports:
      - "8088:8088"        # Web UI YARN
      - "8030:8030"        # Scheduler
      - "8031:8031"        # Resource Tracker
      - "8032:8032"        # Address
      - "8033:8033"        # Admin
    volumes:
      - ./data_share:/data_share
      - ./step_02_hadoop_map_reduce:/scripts
    environment:
      - CORE-SITE.XML_fs.defaultFS=hdfs://hdfs-namenode:9000
      - HDFS-SITE.XML_dfs.replication=1
      - HDFS-SITE.XML_dfs.permissions.enabled=false
      - YARN_RESOURCEMANAGER_USER=root
      # ResourceManager settings
      - YARN-SITE.XML_yarn.resourcemanager.hostname=yarn-resourcemanager
      - YARN-SITE.XML_yarn.resourcemanager.address=yarn-resourcemanager:8032
      - YARN-SITE.XML_yarn.resourcemanager.scheduler.address=yarn-resourcemanager:8030
      - YARN-SITE.XML_yarn.resourcemanager.resource-tracker.address=yarn-resourcemanager:8031
      - YARN-SITE.XML_yarn.log-aggregation-enable=true
      - YARN-SITE.XML_yarn.nodemanager.aux-services=mapreduce_shuffle
      - MAPRED-SITE.XML_mapreduce.framework.name=yarn
      - MAPRED-SITE.XML_mapreduce.jobhistory.address=historyserver:10020
      - MAPRED-SITE.XML_mapreduce.jobhistory.webapp.address=historyserver:19888
      - YARN-SITE.XML_yarn.nodemanager.env-whitelist="JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_MAPRED_HOME"
      - MAPRED-SITE.XML_yarn.app.mapreduce.am.env-whitelist="JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_MAPRED_HOME"
    depends_on:
      - hdfs-namenode #:
        #condition: service_healthy
    command: ["yarn", "resourcemanager"]

# 5. yarn-nodemanager
  yarn-nodemanager:
    image: apache/hadoop:3.5.0
    container_name: yarn-nodemanager
    restart: always
    hostname: yarn-nodemanager
    user: root
    networks:
      - data-net
    ports:
      - "8042:8042"        # Web UI NodeManager
    volumes:
      - ./data_share:/data_share
      - ./step_02_hadoop_map_reduce:/scripts
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - YARN_RESOURCEMANAGER_USER=root
      - YARN_NODEMANAGER_USER=root
      - YARN-SITE.XML_yarn.nodemanager.local-dirs=/hadoop/yarn/local
      - YARN-SITE.XML_yarn.nodemanager.log-dirs=/hadoop/yarn/logs
      # HDFS connection
      - CORE-SITE.XML_fs.defaultFS=hdfs://hdfs-namenode:9000
      - HDFS-SITE.XML_dfs.replication=1
      - HDFS-SITE.XML_dfs.permissions.enabled=false
      # YARN connection
      - YARN-SITE.XML_yarn.resourcemanager.hostname=yarn-resourcemanager
      - YARN-SITE.XML_yarn.resourcemanager.address=yarn-resourcemanager:8032
      - YARN-SITE.XML_yarn.resourcemanager.scheduler.address=yarn-resourcemanager:8030
      - YARN-SITE.XML_yarn.resourcemanager.resource-tracker.address=yarn-resourcemanager:8031
      - YARN-SITE.XML_yarn.log-aggregation-enable=true
      - YARN-SITE.XML_yarn.nodemanager.aux-services=mapreduce_shuffle
      - MAPRED-SITE.XML_mapreduce.framework.name=yarn
      - MAPRED-SITE.XML_mapreduce.jobhistory.address=historyserver:10020
      - MAPRED-SITE.XML_mapreduce.jobhistory.webapp.address=historyserver:19888
      - YARN-SITE.XML_yarn.nodemanager.env-whitelist=JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_MAPRED_HOME
      - MAPRED-SITE.XML_yarn.app.mapreduce.am.env-whitelist=JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_MAPRED_HOME
    depends_on:
      - yarn-resourcemanager #:
        #condition: service_started
      - hdfs-datanode #:
        #condition: service_started
    command: ["yarn", "nodemanager"]

# ========== step_03_spark_aggregation
# 6. spark-jupyter
  spark-jupyter:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: spark-jupyter
    hostname: spark-jupyter
    networks:
      - data-net
    ports:
      - "8888:8888"                   # Jupyter Notebook
      - "4040:4040"                   # Spark Web UI 
    volumes:
      - ./step_03_spark_aggregation:/home/jovyan/work/spark_aggregation           # I still don't understand who tf is Jovyan
      - ./step_04_postgres_datamart:/home/jovyan/work/pg_preparation
      - ./data_share:/home/jovyan/work/data_share
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      # HDFS connection (maybe remove, probs useless)
      - SPARK_OPTS=--master local[*] --conf spark.hadoop.fs.defaultFS=hdfs://hdfs-namenode:9000
    depends_on:
      - hdfs-namenode #:
        # condition: service_healthy
    command: >
      sh -c "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

# ========== step_04_postgres_datamart
# 7. postgres
  db-postgres:
    image: postgres:18.4
    container_name: db-postgres
    restart: always
    networks:
      - data-net
    ports:
    - "5432:5432"
    volumes:
      - ./step_04_postgres_datamart:/host_data
      - ./data_share:/data_share
    environment:
    # IT'S A LOCAL TEST, NOT A PROD
      - POSTGRES_USER=officeguy
      - POSTGRES_PASSWORD=Test4321
      - POSTGRES_DB=customs_db

# 8. pgadmin4
  db-pgadmin4:
    image: dpage/pgadmin4:9.17
    container_name: db-pgadmin4
    restart: always
    networks:
      - data-net
    ports:
    - "5080:80"
    volumes:
      - ./step_04_postgres_datamart:/var/lib/pgadmin/storage
    environment:
    # IT'S A LOCAL TEST, NOT A PROD
      - PGADMIN_DEFAULT_EMAIL=officeguy@admin.com
      - PGADMIN_DEFAULT_PASSWORD=Test4321

# ========== Net Vol
networks:
  data-net:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode: